### ISSUE TITLE
Multiple nodes with the same addr can exist in the table?

### ISSUE THREAD

**Issue by anacrolix** [anacrolix/dht#12]
```
panic: missing addr for node in table

goroutine 12 [running]:
github.com/anacrolix/dht.(*table).dropNode(0xc420089c40, 0xc420b83580)
        /root/gopath/src/github.com/anacrolix/dht/table.go:18 +0x189
github.com/anacrolix/dht.(*Server).getNode.func1(0xc420b83580, 0xc421f183c0)
        /root/gopath/src/github.com/anacrolix/dht/server.go:401 +0x9e
github.com/anacrolix/dht.(*bucket).EachNode(0xc420089d10, 0xc423267da8, 0x9a6e89e182121c52)
        /root/gopath/src/github.com/anacrolix/dht/bucket.go:13 +0x9b
github.com/anacrolix/dht.(*Server).getNode(0xc420089c00, 0xa65200, 0xc4243e86c0, 0xfd6dc2058a36c336, 0x9a6e89e182121c52, 0x11542caa4, 0x0, 0x7f0fc3e799e0, 0x0)
        /root/gopath/src/github.com/anacrolix/dht/server.go:399 +0x19e
github.com/anacrolix/dht.(*Server).processPacket(0xc420089c00, 0xc422058000, 0x68, 0x10000, 0xa65200, 0xc4243e86c0)
        /root/gopath/src/github.com/anacrolix/dht/server.go:217 +0x406
github.com/anacrolix/dht.(*Server).serve(0xc420089c00, 0x0, 0x0)
        /root/gopath/src/github.com/anacrolix/dht/server.go:262 +0x233
github.com/anacrolix/dht.NewServer.func1(0xc4200820e0)
        /root/gopath/src/github.com/anacrolix/dht/server.go:150 +0x32
created by github.com/anacrolix/dht.NewServer
        /root/gopath/src/github.com/anacrolix/dht/server.go:149 +0x2cd
```

**Comment by 0xbzho** [comment]
Came to report the same thing.  LMK if you need help debugging.

```
panic: missing addr for node in table

goroutine 13175557 [running]:
github.com/anacrolix/dht.(*table).dropNode(0xc42008dc40, 0xc4202bac80)
	/home/redacted/src/github.com/anacrolix/dht/table.go:18 +0x189
github.com/anacrolix/dht.(*Server).getNode.func1(0xc4202bac80, 0xc4202e4401)
	/home/redacted/src/github.com/anacrolix/dht/server.go:401 +0x9e
github.com/anacrolix/dht.(*bucket).EachNode(0xc42008dce8, 0xc4208ecd18, 0x35521a48c7d37a33)
	/home/redacted/src/github.com/anacrolix/dht/bucket.go:13 +0x9b
github.com/anacrolix/dht.(*Server).getNode(0xc42008dc00, 0xa296a0, 0xc420353a00, 0x7d2c3ed21ea6fd52, 0x35521a48c7d37a33, 0x1ce28ff50, 0x0, 0xa263e0, 0xc421ee9340)
	/home/redacted/src/github.com/anacrolix/dht/server.go:399 +0x19e
github.com/anacrolix/dht.(*Server).addResponseNodes(0xc42008dc00, 0x0, 0x0, 0x0, 0xc4209834f4, 0x4, 0xc420983581, 0x1, 0xc424ad0480, 0x0, ...)
	/home/redacted/src/github.com/anacrolix/dht/server.go:616 +0x137
github.com/anacrolix/dht.(*Server).getPeers.func1(0x0, 0x0, 0x0, 0xc4209834f4, 0x4, 0xc420983581, 0x1, 0xc424ad0480, 0x0, 0xc4209832e8, ...)
	/home/redacted/src/github.com/anacrolix/dht/server.go:717 +0x128
created by github.com/anacrolix/dht.(*Server).query.func3
	/home/redacted/src/github.com/anacrolix/dht/server.go:536 +0x87
```

**Comment by anacrolix** [comment]
Cheers, I know what it is, I'll push a fix soon.
