### ISSUE TITLE
panic: sync: negative WaitGroup counter

### ISSUE THREAD

**Issue by 0xbzho** [anacrolix/dht#15]
Running r55080c5 I'm regularly getting the following panic. Any ideas, or should I work on a reproduction?

`panic: sync: negative WaitGroup counter`
`goroutine 17787 [running]:`
`sync.(*WaitGroup).Add(0x13984c10, 0xffffffff) /usr/local/go/src/sync/waitgroup.go:73 +0x150`
`sync.(*WaitGroup).Done(0x13984c10) /usr/local/go/src/sync/waitgroup.go:98 +0x24`
`localhost/xxx/vendor/github.com/anacrolix/dht.(*Server).Bootstrap.func1.1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)`
`localhost/xxx/vendor/github.com/anacrolix/dht/server.go:662 +0x13c`
`localhost/xxx/vendor/github.com/anacrolix/dht.(*Server).findNode.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)`
`localhost/xxx/vendor/github.com/anacrolix/dht/server.go:630 +0x80`
`created by localhost/xxx/vendor/github.com/anacrolix/dht.(*Server).query.func4 localhost/xxx/vendor/github.com/anacrolix/dht/server.go:540 +0x88`
`

**Comment by anacrolix** [comment]
I think I can see how this situation could occur. Do you have any log messages like "error resending query: " preceding this panic?

**Comment by 0xbzho** [comment]
I don't. The only other warnings I've ever got were from the torrent library regarding timeouts in locking the boltDB file, but I'm sure those are due to a race on my side. I'll enable debugging.

**Comment by 0xbzho** [comment]
Yeah, the only debug messages preceding the panic are expected:

`client.go:1042: error during connection loop: unexpected EOF`
`client.go:689: error establishing outgoing connection: error reading until VC: read tcp  192.168.1.251:39758->nn.nn.nn.nnn:51413: i/o timeout`

**Comment by anacrolix** [comment]
I think a reproduction will help. Thanks

**Comment by anacrolix** [comment]
Any update on this? Thanks

**Comment by anacrolix** [comment]
I've added a unit test that should reproduce this. Run `go get -u github.com/anacrolix/dht && go test -run BootstrapRace -count 10 -race github.com/anacrolix/dht`.

**Comment by anacrolix** [comment]
Note that the test doesn't require `-race`, it just is more likely to fail with that enabled. Try with `-count 100` and without `-race` if the race detector is not available.

**Comment by axet** [comment]
That what I'm getting on my old and super slow android phone:

```
01-21 14:57:49.930 15909-15935/com.github.axet.torrentclient E/GoLog: 2019-01-21 11:57:49 client.go:328: completed bootstrap, [{*dht.Server [dht server on 0.0.0.0:35212]} {*torrent.Client [0x5b4d01c0]} {dht.TraversalStats [dht.TraversalStats{NumAddrsTried:8314, NumResponses:4269}]}]
01-21 14:57:50.450 15909-15933/com.github.axet.torrentclient E/Go: panic: sync: negative WaitGroup counter
01-21 14:57:50.450 15909-15933/com.github.axet.torrentclient E/Go: goroutine 95679 [running]:
01-21 14:57:50.580 15909-15933/com.github.axet.torrentclient E/Go: sync.(*WaitGroup).Add(0x5b6043b0, 0xffffffff)
01-21 14:57:50.580 15909-15933/com.github.axet.torrentclient E/Go: 	/opt/local/lib/go/src/sync/waitgroup.go:74 +0x170
01-21 14:57:50.580 15909-15933/com.github.axet.torrentclient E/Go: sync.(*WaitGroup).Done(0x5b6043b0)
01-21 14:57:50.580 15909-15933/com.github.axet.torrentclient E/Go: 	/opt/local/lib/go/src/sync/waitgroup.go:99 +0x24
01-21 14:57:50.580 15909-15933/com.github.axet.torrentclient E/Go: github.com/anacrolix/dht.(*Server).Bootstrap.func1.1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
01-21 14:57:50.580 15909-15933/com.github.axet.torrentclient E/Go: 	/Users/axet/source/libtorrent/src/github.com/anacrolix/dht/server.go:738 +0x104
01-21 14:57:50.580 15909-15933/com.github.axet.torrentclient E/Go: github.com/anacrolix/dht.(*Server).findNode.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
01-21 14:57:50.580 15909-15933/com.github.axet.torrentclient E/Go: 	/Users/axet/source/libtorrent/src/github.com/anacrolix/dht/server.go:704 +0x80
01-21 14:57:50.580 15909-15933/com.github.axet.torrentclient E/Go: created by github.com/anacrolix/dht.(*Server).query.func4
01-21 14:57:50.580 15909-15933/com.github.axet.torrentclient E/Go: 	/Users/axet/source/libtorrent/src/github.com/anacrolix/dht/server.go:617 +0x90
01-21 14:57:50.580 15909-15933/com.github.axet.torrentclient A/libc: Fatal signal 6 (SIGABRT) at 0x00003e25 (code=-6)
```
